### ISSUE TITLE
`baad_data_versions("github")` fails

### ISSUE THREAD

**Issue by RemkoDuursma** [traitecoevo/baad.data#7]
Error:

```
Error in if (local) { : argument is not interpretable as logical
```

(windows, baad.data 1.0.1)

**Comment by RemkoDuursma** [comment]
I now see this is because the documentation does not match the actual function arguments.

**Comment by dfalster** [comment]
Sorry, I can't see where the idea to call `baad_data_versions("github")` comes from? perhaps a dolover from an older version?

**Comment by RemkoDuursma** [comment]
Strange - I updated the package but the help file pointed to the old version. Apologies.
